apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      app: flask2
  replicas: 2
  template:
    metadata:
      labels:
        app: flask2
    spec:
      containers:
      - name: flaskapp
        image: appuanil02/mullapudi:version02
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask2
  name: anil-service-lb
spec:
  type: LoadBalancer
  selector:
    app: flask2
  ports:
    - port: 80
      targetPort: 5000
